### ISSUE TITLE
No module named 'console 

### ISSUE THREAD

**Issue by devlop7** [mixmastamyk/console#16]
i have this issue even i have install it and it work but when i convert py to exe i have this issue
```
Traceback (most recent call last):
  File "<dist\obf\main.py>", line 3, in <module>
  File "<frozen main>", line 157, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "<menu_init.py>", line 1, in <module>
  File "<frozen menu_init>", line 6, in <module>
ModuleNotFoundError: No module named 'console'
[12568] Failed to execute script 'main' due to unhandled exception!
```

**Comment by mixmastamyk** [comment]
Hi, I'm not very familiar with pyinstaller.  Looks like on Windows.  

Console is pure python so shouldn't have any install difficulties.

I believe for these type of installers you need to list the packages you require in a config file.

**Comment by Krutyi-4el** [comment]
Hello

PyInstaller can't recognise `# -*- coding: future_fstrings -*-` and skips the module.
Install `future_fstrings` module to build the executable successfully.

**Comment by mixmastamyk** [comment]
future_fstrings was removed in .9908.  So shouldn't need this workaround for pyinstaller any longer.
