### ISSUE TITLE
Unresponsive in VS Code Terminal

### ISSUE THREAD

**Issue by devsys** [mixmastamyk/console#3]
Greetings, 

I am using the terminal in Visual Studio Code on Ubuntu 18.04.1 LTS. I have the following code:

```
from console import fg, bg, fx

print(fg.navyblue + 'Hello World!' + fg.default)
print(fg.red, fx.italic, '♥ Heart', fx.end, ' python…', sep='')
print(fg.yellow('Woot!'))  # --> '\x1b[33mWoot!\x1b[39m'
```

When I run this inside VS Code, it seems to freeze and go into a loop until Ctl+C is hit, and I get this output:

```
$ python3 consoleTest.py 
Traceback (most recent call last):
  File "consoleTest.py", line 1, in <module>
    from console import fg, bg, fx
  File "/home/nate/python-dev/sshMan/.venv/lib/python3.6/site-packages/console/__init__.py", line 44, in <module>
    _CHOSEN_PALETTE = _choose_palette()
  File "/home/nate/python-dev/sshMan/.venv/lib/python3.6/site-packages/console/detection.py", line 95, in choose_palette
    result, pal = detect_palette_support(basic_palette=pal)
  File "/home/nate/python-dev/sshMan/.venv/lib/python3.6/site-packages/console/detection.py", line 199, in detect_palette_support
    name, pal_name, basic_palette = _find_basic_palette(name)
  File "/home/nate/python-dev/sshMan/.venv/lib/python3.6/site-packages/console/detection.py", line 307, in _find_basic_palette
    if get_color('index', 2)[0][:2] == '85':
  File "/home/nate/python-dev/sshMan/.venv/lib/python3.6/site-packages/console/detection.py", line 497, in get_color
    colors = _get_color_xterm(name, number)
  File "/home/nate/python-dev/sshMan/.venv/lib/python3.6/site-packages/console/detection.py", line 415, in _get_color_xterm
    resp = _read_until(maxchars=26, end=(BEL, ST)).rstrip(ESC)
  File "/home/nate/python-dev/sshMan/.venv/lib/python3.6/site-packages/console/detection.py", line 390, in _read_until
    char = read(1)
KeyboardInterrupt
```
Seems like it's blowing up doing some detection or something. I plan to try this test under VS Code on Windows with WSL to see if it has the same result. I'm guessing MS is doing something weird as usual...

The same code works fine if I pop open a regular terminal outside VS Code:

```
$ python3 consoleTest.py 
Hello World!
♥ Heart python…
Woot!
```

**Comment by mixmastamyk** [comment]
Thanks, had a feeling that might be a problem at some point.

It does some querying when the terminal tells it that it is an xterm/compatible.  However some lie and don't fully support it.  Must be an example.

Try this environment variable to shut it off temporarily: `PY_CONSOLE_AUTODETECT=0`
and I'll look into what is causing it shortly.

**Comment by devsys** [comment]
Yep, that fixed the hanging!

I get the following output with the env var set... there are no colors in the output, but it runs and isn't broken, so I'd consider that a win!

```
$ python3 consoleTest.py 
Hello World!
♥ Heart python…
Woot!
```
Thanks!

**Comment by mixmastamyk** [comment]
I'll download the editor to see what it reports.  If you turn on DEBUG logging before console you can see what it says, if you are interested in the investigation as well:

https://mixmastamyk.bitbucket.io/console/additional.html#troubleshooting

**Comment by mixmastamyk** [comment]
Powershell?

**Comment by devsys** [comment]
No, I'm using bash in the Visual Studio Code terminal. I'm running VS Code under Linux, so I suspect this is different than if you try the same thing in Windows which would likely use all the WSL stuff.

I turned on debug logging in my test script:

```
$ python3 consoleTest.py 
  DEBUG   detection/choose_palette:88 console version: 0.96
  DEBUG   detection/color_is_forced:149 None (CLICOLOR_FORCE=None)
  DEBUG   detection/is_a_tty:348 True
  DEBUG   detection/color_is_disabled:125 None (NO_COLOR=None, CLICOLOR=None)
  DEBUG   detection/is_a_tty:348 True
```

**Comment by mixmastamyk** [comment]
How about with the env var?  Looks like it is stopping a little soon.  Curious what TERM is, etc.

**Comment by mixmastamyk** [comment]
It is probably confused what OS it is on.  😂

**Comment by devsys** [comment]
Hah yeah it's weirdly wonderful that I can do this and honestly it works great. 

env looks like this -- I dont have any funky configs, this should be what you get:

```
CLUTTER_IM_MODULE=xim
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_MENU_PREFIX=gnome-
LANG=en_US.UTF-8
DISPLAY=:0
GNOME_SHELL_SESSION_MODE=ubuntu
USERNAME=devsys
CHROME_DESKTOP=code-url-handler.desktop
NO_AT_BRIDGE=1
XDG_VTNR=1
GIO_LAUNCHED_DESKTOP_FILE_PID=12096
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
VIRTUAL_ENV=/home/devsys/python-dev/sshMan/.venv
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
XDG_SESSION_ID=1
USER=devsys
DESKTOP_SESSION=ubuntu
QT4_IM_MODULE=xim
TEXTDOMAINDIR=/usr/share/locale/
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
PWD=/home/devsys/python-dev/sshMan
HOME=/home/devsys
TEXTDOMAIN=im-config
SSH_AGENT_PID=1622
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.34.0
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_SESSION_DESKTOP=ubuntu
GJS_DEBUG_OUTPUT=stderr
GTK_MODULES=gail:atk-bridge
PY_CONSOLE_AUTODETECT=1
WINDOWPATH=1
TERM=xterm-256color
SHELL=/bin/bash
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
IM_CONFIG_PHASE=2
XDG_CURRENT_DESKTOP=Unity
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/code.desktop
SHLVL=2
XDG_SEAT=seat0
GDMSESSION=ubuntu
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=devsys
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/run/user/1000/gdm/Xauthority
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
PATH=/home/devsys/python-dev/sshMan/.venv/bin:/home/devsys/.local/bin:/home/devsys/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PS1=(.venv) \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ 
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
SESSION_MANAGER=local/badger:@/tmp/.ICE-unix/1525,unix/badger:/tmp/.ICE-unix/1525
LESSOPEN=| /usr/bin/lesspipe %s
GTK_IM_MODULE=ibus
```

**Comment by mixmastamyk** [comment]
Ok, misunderstood, thought you were on Windows for a minute.  Tried latest on VSC under Windows and it worked.  Will download and try on Ubuntu now.

**Comment by mixmastamyk** [comment]
Ok, I turned that off for vscode on posix and and am thinking about deactivating entirely.  Published a new version of console: `0.97a1`

Please give it a try and let me know if it fixes the problem.  Probably need to use something like:
`pip3 install -U --pre console`

**Comment by mixmastamyk** [comment]
I also put in a timeout with select for all read functions, so they should never hang more than a moment.

**Comment by devsys** [comment]
I updated and it works great now (colors included):

```
$ python3 consoleTest.py 
  DEBUG   detection/choose_palette:89 console version: 0.97a2
  DEBUG   detection/choose_palette:90 os.name/sys.platform: posix/linux
  DEBUG   detection/color_is_forced:151 None (CLICOLOR_FORCE=None)
  DEBUG   detection/is_a_tty:351 True
  DEBUG   detection/color_is_disabled:127 None (NO_COLOR=None, CLICOLOR=None)
  DEBUG   detection/is_a_tty:351 True
  DEBUG   detection/_find_basic_palette:319 get_color return value failed: tuple index out of range
  DEBUG   detection/detect_palette_support:209 Term support: 'extended' (posix, TERM=xterm-256color, COLORTERM=, ANSICON=, webcolors=False, basic_palette=default (xterm))
  DEBUG   detection/choose_palette:100 Basic palette: ((0, 0, 0), (205, 0, 0), (0, 205, 0), (205, 205, 0), (0, 0, 238), (205, 0, 205), (0, 205, 205), (229, 229, 229), (127, 127, 127), (255, 0, 0), (0, 255, 0), (255, 255, 0), (92, 92, 255), (255, 0, 255), (0, 255, 255), (255, 255, 255))
  DEBUG   detection/choose_palette:101 'extended' is available
Hello World!
♥ Heart python…
Woot!
```

Thanks!

**Comment by mixmastamyk** [comment]
Thanks for letting me know.

**Comment by mixmastamyk** [comment]
I'd like to keep this open a bit, as I'm not ready to push a non-pre release yet, and it will be informative to vscode users.

**Comment by mixmastamyk** [comment]
Now in .98 as well.
